Repository depromeet/momuzzi-server, pull requests merged in 2025-09, with the labels that each got.

#9 [SETTING] 서버 인프라 세팅
  .gitignore
  docker-compose.yml
  infra/nginx/nginx.conf
  module-api/Dockerfile
  module-api/build.gradle.kts
  module-api/src/main/resources/application-prod.yml
  module-api/src/main/resources/application.yml
Labels: ⚙️ SETTING

#10 [SETTING] Private Docker Registry Setting
  .gitignore
  docker-compose.prod.yml
  docker-compose.registry.yml
  module-infra/nginx/nginx.conf
Labels: ⚙️ SETTING

#13 [SETTING] 코틀린 jdsl 설정 추가
  module-infra/build.gradle.kts
Labels: ⚙️ SETTING

#22 [REFACTOR] 모임 참가 검증
  module-api/src/main/kotlin/org/depromeet/team3/meeting/application/InviteTokenService.kt
  module-api/src/main/kotlin/org/depromeet/team3/meeting/application/JoinMeetingService.kt
  module-api/src/main/kotlin/org/depromeet/team3/meeting/controller/MeetingController.kt
  module-api/src/main/kotlin/org/depromeet/team3/meeting/dto/response/MeetingResponse.kt
  module-api/src/main/kotlin/org/depromeet/team3/meeting/dto/response/ValidateInviteTokenResponse.kt
  module-api/src/test/kotlin/org/depromeet/team3/meeting/application/InviteTokenServiceTest.kt
Labels: ♻️ REFACTOR

#24 [FEATURE] Add Jenkins Workflow Trigger
  Jenkinsfile
Labels: ✨ FEATURE

#23 [FEATURE] KaKao OAuth Login
  module-api/build.gradle.kts
  module-api/src/main/kotlin/org/depromeet/team3/auth/application/AuthService.kt
  module-api/src/main/kotlin/org/depromeet/team3/auth/application/response/UserProfileResponse.kt
  module-api/src/main/kotlin/org/depromeet/team3/auth/presentation/AuthController.kt
  module-api/src/main/kotlin/org/depromeet/team3/security/SecurityConfig.kt
  module-api/src/main/kotlin/org/depromeet/team3/security/jwt/JwtAuthenticationFilter.kt
  module-api/src/main/kotlin/org/depromeet/team3/security/jwt/JwtAuthenticationToken.kt
  module-api/src/main/kotlin/org/depromeet/team3/security/jwt/JwtProperties.kt
  module-api/src/main/kotlin/org/depromeet/team3/security/jwt/JwtTokenProvider.kt
  module-api/src/main/kotlin/org/depromeet/team3/security/util/CookieUtil.kt
  module-api/src/main/resources/application-prod.yml
  module-api/src/main/resources/application.yml
  module-domain/src/main/kotlin/org/depromeet/team3/auth/exception/AuthException.kt
  module-domain/src/main/kotlin/org/depromeet/team3/common/exception/ErrorCode.kt
  module-domain/src/main/kotlin/org/depromeet/team3/user/User.kt
  module-infra/build.gradle.kts
  module-infra/src/main/kotlin/org/depromeet/team3/auth/KakaoOAuthClient.kt
  module-infra/src/main/kotlin/org/depromeet/team3/auth/KakaoProperties.kt
  module-infra/src/main/kotlin/org/depromeet/team3/auth/model/KakaoResponse.kt
  module-infra/src/main/kotlin/org/depromeet/team3/mapper/MeetingAttendeeMapper.kt
  module-infra/src/main/kotlin/org/depromeet/team3/mapper/MeetingMapper.kt
  module-infra/src/main/kotlin/org/depromeet/team3/mapper/UserMapper.kt
  module-infra/src/main/kotlin/org/depromeet/team3/user/UserEntity.kt
  module-infra/src/main/kotlin/org/depromeet/team3/user/UserJpaRepository.kt
  module-infra/src/main/kotlin/test.txt
Labels: ✨ FEATURE

#28 [SETTING] 프론트 배포용 docker-compose 설정
  srv/momuzzi/deploy/compose.yaml
Labels: ⚙️ SETTING

#32 [SETTING] SecurityTestConfig 추가, 직렬화, validation 관련 의존성 추가
  module-api/build.gradle.kts
  module-api/src/main/kotlin/org/depromeet/team3/config/ControllerAdvice.kt
  module-api/src/test/kotlin/org/depromeet/team3/config/SecurityTestConfig.kt
Labels: ⚙️ SETTING, 🥡 CHORE

#33 [FEATURE] ENUM 기반 설문 카테고리 CRUD API 구현
  module-api/src/main/kotlin/org/depromeet/team3/config/ControllerAdvice.kt
  module-api/src/main/kotlin/org/depromeet/team3/surveycategory/application/CreateSurveyCategoryService.kt
  module-api/src/main/kotlin/org/depromeet/team3/surveycategory/application/DeleteSurveyCategoryService.kt
  module-api/src/main/kotlin/org/depromeet/team3/surveycategory/application/GetSurveyCategoryService.kt
  module-api/src/main/kotlin/org/depromeet/team3/surveycategory/application/UpdateSurveyCategoryService.kt
  module-api/src/main/kotlin/org/depromeet/team3/surveycategory/controller/SurveyCategoryController.kt
  module-api/src/main/kotlin/org/depromeet/team3/surveycategory/dto/request/CreateSurveyCategoryRequest.kt
  module-api/src/main/kotlin/org/depromeet/team3/surveycategory/dto/request/UpdateSurveyCategoryRequest.kt
  module-api/src/main/kotlin/org/depromeet/team3/surveycategory/dto/response/SurveyCategoryItem.kt
  module-api/src/main/kotlin/org/depromeet/team3/surveycategory/dto/response/SurveyCategoryResponse.kt
  module-api/src/test/kotlin/org/depromeet/team3/surveycategory/application/DeleteSurveyCategoryServiceTest.kt
  module-api/src/test/kotlin/org/depromeet/team3/surveycategory/application/UpdateSurveyCategoryServiceTest.kt
  module-api/src/test/kotlin/org/depromeet/team3/surveycategory/controller/SurveyCategoryControllerTest.kt
  module-domain/src/main/kotlin/org/depromeet/team3/common/exception/DpmException.kt
  module-domain/src/main/kotlin/org/depromeet/team3/common/exception/ErrorCode.kt
  module-domain/src/main/kotlin/org/depromeet/team3/surveycategory/SurveyCategory.kt
  module-domain/src/main/kotlin/org/depromeet/team3/surveycategory/SurveyCategoryLevel.kt
  module-domain/src/main/kotlin/org/depromeet/team3/surveycategory/SurveyCategoryRepository.kt
  module-domain/src/main/kotlin/org/depromeet/team3/surveycategory/SurveyCategoryType.kt
  module-domain/src/main/kotlin/org/depromeet/team3/surveycategory/exception/SurveyCategoryException.kt
  module-domain/src/test/kotlin/org/depromeet/team3/surveycategory/SurveyCategoryLevelTest.kt
  module-domain/src/test/kotlin/org/depromeet/team3/surveycategory/SurveyCategoryTest.kt
  module-domain/src/test/kotlin/org/depromeet/team3/surveycategory/SurveyCategoryTypeTest.kt
  module-infra/src/main/kotlin/org/depromeet/team3/mapper/SurveyCategoryMapper.kt
  module-infra/src/main/kotlin/org/depromeet/team3/surveycategory/SurveyCategoryEntity.kt
  module-infra/src/main/kotlin/org/depromeet/team3/surveycategory/SurveyCategoryJpaRepository.kt
  module-infra/src/main/kotlin/org/depromeet/team3/surveycategory/SurveyCategoryQuery.kt
Labels: ✨ FEATURE
